---
- hosts: osx
  vars:
    do_osx_provision: true
  vars_files:
    - private_vars/osx.yml
  roles:
    - role: geerlingguy.homebrew
      homebrew_installed_packages:
        - ansible
        - autoconf
        - bash
        - bash-completion
        - byobu
        - composer
        - deployer
        - dnsmasq
        - dpkg
        - geoip
        - git
        - git-flow-avh
        - go
        - henkrehorst/php/valet-php@7.4
        - henkrehorst/php/valet-php@8.0
        - henkrehorst/php/valet-php@8.2
        - httpd
        - hub
        - ifuse
        - libiconv
        - libmemcached
        - libxml2
        - lsusb
        - lsyncd
        - lua
        - mailhog
        - mariadb
        - mariadb@10.4
        - mysql-utilities
        - nginx
        - nmap
        - nvm
        - phpunit
        - platformio
        - po4a
        - pv
        - pyenv-virtualenv
        - python@2
        - rbenv
        - redis
        - rename
        - sphinx-doc
        - the_silver_searcher
        - tig
        - travis
        - tree
        - twilio/brew/twilio
        - vcprompt
        - wget
        - wp-cli
        - yarn
        - zlib
        - zsh
        - zsh-history-substring-search

        # Taps
        - box

      homebrew_taps:
        - homebrew/core
        - homebrew/cask
        - henkrehorst/php
        - henkrehorst/bc
        - twilio/brew
        - homebrew/cask-fonts

      homebrew_cask_apps:
        - 1password
        - 1password-cli
        - alfred
        - cloudapp
        - discord
        - docker
        - dropbox
        - droplr
        - ezeep
        - firefox
        - flow
        - focus
        - gimp
        - github
        - google-chrome
        - gpg-suite
        - insomnia
        - keybase
        - launchcontrol
        - osxfuse
        - poedit
        - qbserve
        - sequel-ace
        - skype
        - slack
        - textexpander
        - transmit
        - visual-studio-code

      homebrew_user: jpry
      homebrew_group: admin

    - common
