---
# defaults file for invoiceplane

ip_install_name: invoiceplane
ip_web_root: "/var/www/{{ ip_install_name }}"
ip_git_url: https://github.com/InvoicePlane/InvoicePlane.git
ip_git_version: v1.5.5
ip_domain: "{{ ansible_fqdn }}"
ip_url: "http://{{ ip_domain }}"
ip_db_user: "{{ ip_install_name }}"
ip_db_name: "{{ ip_install_name }}"

# These should be string values, not booleans
ip_remove_indexphp: "false"
ip_disable_invoice_readonly: "false"
ip_disable_setup: "false"
