---
# tasks file for common
- name: Install dotfiles
  git: dest="~/dotfiles" repo="https://github.com/JPry/dotfiles.git" force=yes
  register: dotfiles_updated

- name: Echo dotfiles result
  debug:
    var: dotfiles_updated
    verbosity: 3

- name: Run dotfiles installer
  shell: install/symlinks.sh
  args:
    chdir: ~/dotfiles
    executable: /bin/bash
  when: dotfiles_updated.changed

- name: Install Gems
  become: true
  gem: name="{{ item }}" state=latest user_install=false include_doc=true
  with_items: "{{ ruby_gems }}"
  when: do_gems == true

- name: Insall Oh My Zsh
  git: dest="~/.oh-my-zsh" repo="https://github.com/robbyrussell/oh-my-zsh.git"
