---
# OS X defaults

# osx_defaults: key= domain=NSGlobalDomain state=present type=string value=

###############################################################################
# General UI/UX                                                               #
###############################################################################

- name: Set the theme to dark mode
  osx_defaults:
    domain: /Library/Preferences/.GlobalPreferences
    key: AppleInterfaceTheme
    value: Dark
  become: yes

- name: Show battery percentage
  osx_defaults: domain=com.apple.menuextra.battery key=ShowPercent type=string value=YES

- name: Automatic scroll bars
  osx_defaults: key=AppleShowScrollBars value=Automatic

- name: Highlight color
  osx_defaults: key=AppleHighlightColor value="0.764700 0.976500 0.568600"

- name: Medium sidebar icons
  osx_defaults: key=NSTableViewDefaultSizeMode type=int value=2

- name: Expand save panel by default
  osx_defaults: key={{ item }} type=bool value=true
  with_items:
    - NSNavPanelExpandedStateForSaveMode
    - NSNavPanelExpandedStateForSaveMode2

- name: Expand print panel by default
  osx_defaults: key={{ item }} type=bool value=true
  with_items:
    - PMPrintingExpandedStateForPrint
    - PMPrintingExpandedStateForPrint2

- name: Save to disk (not iCloud) by default
  osx_defaults: key=NSDocumentSaveNewDocumentsToCloud type=bool value=false

- name: Automatically quit printer app when print jobs complete
  osx_defaults: domain=com.apple.print.PrintingPrefs key="Quit When Finished" type=bool value=true

- name: Disable "Are you sure you want to open this Application?" dialog
  osx_defaults: domain=com.apple.LaunchServices key=LSQuarantine type=bool value=false

- name: Extra info when clicking on Clock in the login window
  osx_defaults: domain=com.apple.loginwindow key=AdminHostInfo value=HostName

- name: Check for software updates daily
  osx_defaults: domain=com.apple.SoftwareUpdate key=ScheduleFrequency type=int value=1

- name: Disable smart quotes & dashes
  osx_defaults: key={{ item }} type=bool value=false
  with_items:
    - NSAutomaticDashSubstitutionEnabled
    - NSAutomaticQuoteSubstitutionEnabled


###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################


- name: Enable tapping with trackpad
  osx_defaults: key=com.apple.mouse.tapBehavior type=int value=1

- name: Enable tapping for external trackpad
  osx_defaults: domain=com.apple.driver.AppleBluetoothMultitouch.trackpad key=Clicking type=int value=1

- name: Increase sound quality for Bluetooth headphones/headsets
  osx_defaults: domain=com.apple.BluetoothAudioAgent key="Apple Bitpool Min (editable)" type=int value=40

- name: Enable keyboard access for all controls
  osx_defaults: key=AppleKeyboardUIMode type=int value=3

- name: Set fast keyboard repeat rate
  osx_defaults: key=KeyRepeat type=int value=0
  become: true

# Array values are broken, so this is disabled for now.
#- name: Set languages
#  osx_defaults:
#    key: AppleLanguages
#    type: array
#    value: ["en"]

- name: Set Locale
  osx_defaults: key=AppleLocale value="en_US@currency=USD"

- name: Set measurement units
  osx_defaults: key=AppleMeasurementUnits value="Inches"

- name: Disable metric units
  osx_defaults: key=AppleMetricUnits type=bool value=false


###############################################################################
# Screen                                                                      #
###############################################################################


- name: Require password after sleep/screensaver
  osx_defaults: domain=com.apple.screensaver key=askForPassword type=int value=1

- name: Require password 5s after sleep/screensaver
  osx_defaults: domain=com.apple.screensaver key=askForPasswordDelay type=float value=5

- name: Save screenshots to desktop
  osx_defaults: domain=com.apple.screencapture key=location value="${HOME}/Pictures/Screenshots"
  become: true

- name: Save screenshots in PNG format
  osx_defaults: domain=com.apple.screencapture key=type value="png"

- name: Disable shadows in screenshots
  osx_defaults: domain=com.apple.screencapture key=disable-shadow type=bool value=true

- name: Enable subpixel rendering on non-apple LCDs
  osx_defaults: key=AppleFontSmoothing type=int value=2

- name: Enable HiDPI display modes
  osx_defaults: domain=com.apple.windowserver key=DisplayResolutionEnabled type=bool value=true


###############################################################################
# Finder                                                                      #
###############################################################################


- name: Allow quitting Finder via ⌘ + Q, which will hide desktop icons
  osx_defaults: domain=com.apple.finder key=QuitMenuItem type=bool value=true

- name: Show icons for hard drives, servers, and removable media on desktop
  osx_defaults: domain=com.apple.finder key={{ item }} type=bool value=true
  with_items:
    - ShowExternalHardDrivesOnDesktop
    - ShowHardDrivesOnDesktop
    - ShowMountedServersOnDesktop
    - ShowRemovableMediaOnDesktop

- name: Show hidden files by default
  osx_defaults: domain=com.apple.finder key=AppleShowAllFiles type=bool value=true

- name: Show all filename extensions
  osx_defaults: key=AppleShowAllExtensions type=bool value=true

- name: Show status bar
  osx_defaults: domain=com.apple.finder key=ShowStatusBar type=bool value=true

- name: Show path bar
  osx_defaults: domain=com.apple.finder key=ShowPathbar type=bool value=true

- name: Allow text selection in quick look
  osx_defaults: domain=com.apple.finder key=QLEnableTextSelection type=bool value=true

- name: POSIX path as finder window title
  osx_defaults: domain=com.apple.finder key=_FXShowPosixPathInTitle type=bool value=true

- name: Search current folder by default
  osx_defaults: domain=com.apple.finder key=FXDefaultSearchScope value="SCcf"

- name: Disable warning when changing file extension
  osx_defaults: domain=com.apple.finder key=FXEnableExtensionChangeWarning type=bool value=false

- name: Enable spring loading for directories
  osx_defaults: key=com.apple.springing.enabled type=bool value=true

- name: Remove spring loading delay for directories
  osx_defaults: key=com.apple.springing.delay type=float value=0

- name: No .DS_Store files on network volumes
  osx_defaults: domain=com.apple.desktopservices key=DSDontWriteNetworkStores type=bool value=true

- name: Disable disk image verification
  osx_defaults: domain=com.apple.frameworks.diskimages key={{ item }} type=bool value=true
  with_items:
    - skip-verify
    - skip-verify-locked
    - skip-verify-remote

- name: Automatically open a finder window when a volume is mounted
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: "{{ item }}"
    type: bool
    value: true
  with_items:
    - auto-open-ro-root
    - auto-open-rw-root

- name: Open finder for removable disk
  osx_defaults: domain=com.apple.finder key=OpenWindowForNewRemovableDisk type=bool value=true

- name: Enable snap-to-grid for icons on desktop and other views
  shell: /usr/libexec/PlistBuddy -c "{{ item }}" ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid"
    - "Set :StandardViewSettings:IconViewSettings:arrangeBy grid"
    - "Set :StandardViewSettings:IconViewSettings:arrangeBy grid"

- name: Increase grid spacing for icons on desktop and other views
  shell: /usr/libexec/PlistBuddy -c "{{ item }}" ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - "Set :DesktopViewSettings:IconViewSettings:gridSpacing 100"
    - "Set :StandardViewSettings:IconViewSettings:gridSpacing 100"
    - "Set :StandardViewSettings:IconViewSettings:gridSpacing 100"

- name: Increase size of icons on desktop and other views
  shell: /usr/libexec/PlistBuddy -c "{{ item }}" ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - "Set :DesktopViewSettings:IconViewSettings:iconSize 80"
    - "Set :StandardViewSettings:IconViewSettings:iconSize 80"
    - "Set :StandardViewSettings:IconViewSettings:iconSize 80"

- name: Use column view in Finder by default
  osx_defaults: domain=com.apple.finder key=FXPreferredViewStyle value="clmv"

- name: Disable warning before emptying trash
  osx_defaults: domain=com.apple.finder key=WarnOnEmptyTrash type=bool value=false

- name: Empty trash securely by default
  osx_defaults: domain=com.apple.finder key=EmptyTrashSecurely type=bool value=true

- name: Enable AirDrop over ethernet and on unsupported Macs running Lion
  osx_defaults: domain=com.apple.NetworkBrowser key=BrowseAllInterfaces type=bool value=true

- name: Show the ~/Library folder
  shell: chflags nohidden ~/Library


###############################################################################
# Dock, Dashboard, and hot corners                                            #
###############################################################################


- name: Enable highlight hover effect for grid view of stack (Dock)
  osx_defaults: domain=com.apple.dock key=mouse-over-hilite-stack type=bool value=true

- name: Minimize windows into application icon
  osx_defaults: domain=com.apple.dock key=minimize-to-application type=bool value=true

- name: Enable spring loading for all dock items
  osx_defaults: domain=com.apple.dock key=enable-spring-load-actions-on-all-items type=bool value=true

- name: Show indicator lights for open apps in the dock
  osx_defaults: domain=com.apple.dock key=show-process-indicators type=bool value=true

- name: Speed up mission control animations
  osx_defaults: domain=com.apple.dock key=expose-animation-duration type=float value=0.1

- name: Don't show dashboard as a Space
  osx_defaults: domain=com.apple.dock key=dashboard-in-overlay type=bool value=true

- name: Don't automatically rearrange spaces
  osx_defaults: domain=com.apple.dock key=mru-spaces type=bool value=false

- name: Remove auto-hiding dock delay
  osx_defaults: domain=com.apple.dock key=autohide-delay type=float value=0

- name: Automatically hide/show the dock
  osx_defaults: domain=com.apple.dock key=autohide type=bool value=true

- name: Make Dock icons of hidden applications translucent
  osx_defaults: domain=com.apple.dock key=showhidden type=bool value=true

- name: Enable Dock magnification
  osx_defaults: domain=com.apple.dock key=magnification type=bool value=true

- name: Set up the large size for the Dock icons
  osx_defaults: domain=com.apple.dock key=largesize type=int value=98

  # Hot corners
  # Possible values:
  #  0: no-op
  #  2: Mission Control
  #  3: Show application windows
  #  4: Desktop
  #  5: Start screen saver
  #  6: Disable screen saver
  #  7: Dashboard
  # 10: Put display to sleep
  # 11: Launchpad
  # 12: Notification Center
- name: Setup Hot Corners
  osx_defaults:
    domain: com.apple.dock
    key: "wvous-{{ item.key }}-corner"
    type: int
    value: "{{ item.value }}"
  with_items:
    - key: bl
      value: 4
    - key: br
      value: 3
    - key: tl
      value: 5
    - key: tr
      value: 7

- name: Setup Hot Corners modifiers
  osx_defaults:
    domain: com.apple.dock
    key: "wvous-{{ item }}-modifier"
    type: int
    value: 0
  with_items:
    - bl
    - br
    - tl
    - tr


###############################################################################
# Safari & WebKit                                                             #
###############################################################################


- name: Don't send search queries to Apple
  osx_defaults: domain=com.apple.Safari key=UniversalSearchEnabled type=bool value=false

- name: Suppress search suggestions
  osx_defaults: domain=com.apple.Safari key=SuppressSearchSuggestions type=bool value=true

- name: Press Tab to highlight each item on a web page
  osx_defaults: domain=com.apple.Safari key=WebKitTabToLinksPreferenceKey type=bool value=true

- name: Tabs to links on webpage
  osx_defaults: domain=com.apple.Safari key=com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks type=bool value=true

- name: Show full URL in the address bar
  osx_defaults: domain=com.apple.Safari key=ShowFullURLInSmartSearchField type=bool value=true

- name: Prevent Safari from opening "safe" files automatically
  osx_defaults: domain=com.apple.Safari key=AutoOpenSafeDownloads type=bool value=false

- name: Hide Safari's bookmarks bar by deafult
  osx_defaults: domain=com.apple.Safari key=ShowFavoritesBar type=bool value=false

- name: Hide Safari's sidebar in top sites
  osx_defaults: domain=com.apple.Safari key=ShowSidebarInTopSites type=bool value=false

- name: Disable Safari's thumbnail cache
  osx_defaults: domain=com.apple.Safari key=DebugSnapshotsUpdatePolicy type=int value=2

- name: Enable Safari's debug menu
  osx_defaults: domain=com.apple.Safari key=IncludeInternalDebugMenu type=bool value=true

- name: Make Safari's search banners defaul to Contains instead of Starts With
  osx_defaults: domain=com.apple.Safari key=FindOnPageMatchesWordStartsOnly type=bool value=false

- name: Remove useless icons from Safari's bookmarks bar
  osx_defaults: domain=com.apple.Safari key=ProxiesInBookmarksBar state=absent

- name: Enable the Develop menu and the Web Inspector in Safari
  osx_defaults: domain=com.apple.Safari key={{ item }} type=bool value=true
  with_items:
    - IncludeDevelopMenu
    - WebKitDeveloperExtrasEnabledPreferenceKey
    - com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled

- name: Add context menu item for showing web inspector in web views
  osx_defaults: key=WebKitDeveloperExtras type=bool value=true


###############################################################################
# Mail                                                                        #
###############################################################################


- name: Copy email addresses as 'foo@example.com' instead of 'Foo Bar <foo@example.com>'
  osx_defaults: domain=com.apple.mail key=AddressesIncludeNameOnPasteboard type=bool value=false

- name: Disable inline attachments
  osx_defaults: domain=com.apple.mail key=DisableInlineAttachmentViewing type=bool value=true


###############################################################################
# Time Machine                                                                #
###############################################################################


- name: Prevent Time Machine from prompting to use new hard drives as backup volume
  osx_defaults: domain=com.apple.TimeMachine key=DoNotOfferNewDisksForBackup type=bool value=true


###############################################################################
# Activity Monitor                                                            #
###############################################################################


- name: Show the main window when launching the Activity Monitor
  osx_defaults: domain=com.apple.ActivityMonitor key=OpenMainWindow type=bool value=true

- name: Visualize CPU usage in the Activity Monitor Dock icon
  osx_defaults: domain=com.apple.ActivityMonitor key=IconType type=int value=5

- name: Show all processes in Activity Monitor
  osx_defaults: domain=com.apple.ActivityMonitor key=ShowCategory type=int value=0

- name: Sort Activity Monitor results by CPU usage
  osx_defaults: domain=com.apple.ActivityMonitor key=SortColumn value="CPUUsage"

- name: Sort activity monitor direction
  osx_defaults: domain=com.apple.ActivityMonitor key=SortDirection type=int value=0


###############################################################################
# Address Book, Dashboard, iCal, TextEdit, and Disk Utility                   #
###############################################################################


- name: Enable the debug menu in Address Book
  osx_defaults: domain=com.apple.addressbook key=ABShowDebugMenu type=bool value=true

- name: Enable Dashboard Dev mode
  osx_defaults: domain=com.apple.dashboard key=devmode type=bool value=true

- name: Enable the debug menu in iCal
  osx_defaults: domain=com.apple.iCal key=IncludeDebugMenu type=bool value=true

- name: Use plain text mode for new TextEdit documents
  osx_defaults: domain=com.apple.TextEdit key=RichText type=int value=0

- name: Open and save files as UTF-8 in TextEdit
  osx_defaults: domain=com.apple.TextEdit key={{ item }} type=int value=4
  with_items:
    - PlainTextEncoding
    - PlainTextEncodingForWrite

- name: Enable debug menu in Disk Utility
  osx_defaults: domain=com.apple.DiskUtility key={{ item }} type=bool value=true
  with_items:
    - DUDebugMenuEnabled
    - advanced-image-options


###############################################################################
# Mac App Store                                                               #
###############################################################################


- name: Enable the WebKit Developer Tools in the Mac App Store
  osx_defaults: domain=com.apple.appstore key=WebKitDeveloperExtras type=bool value=true

- name: Enable Debug Menu in the Mac App Store
  osx_defaults: domain=com.apple.appstore key=ShowDebugMenu type=bool value=true


###############################################################################
# Terminal                                                                    #
###############################################################################

- name: Keep windows when closing the terminal
  osx_defaults:
    domain: com.apple.terminal
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: true

- name: Use Pro as the default Terminal window
  osx_defaults:
    domain: com.apple.terminal
    key: Default Window Settings
    value: Pro
