---
# Tasks related to installing homebrew

- name: Ensure Homebrew is installed
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/Cellar
    executable: /bin/bash

- name: Update/Upgrade Homebrew
  homebrew: update_homebrew=yes upgrade_all=yes
  when: homebrew_update

- name: Install Homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{ brew_taps }}"

- name: Install Homebrew formulae
  homebrew: name={{ item }} state=present
  with_items: "{{ brew_install }}"

- name: Install Homebrew formulae with options
  homebrew: name={{ item }} state=head
  with_items: "{{ brew_install_head }}"
